version: "3.7"

services:
    myownnews:
      networks:
        internal:
          aliases:
            - myownnews
        dmz:
          aliases:
            - myownnews
      env_file:
        - ./environment

networks:
    dmz:
        name: dmz
        external: true
    internal:
        name: internal
